import sys
import os
import json
import numpy as np
import sys
print(sys.executable)
import suite2p
from suite2p import io, registration

#sUITE2p Call

tiff_path = sys.argv[1]
out_dir   = sys.argv[2]
tiff_dir  = os.path.dirname(tiff_path)

ops = suite2p.default_ops()
ops["nplanes"]       = 1
ops["nchannels"]     = 1
ops["do_registration"] = True
ops["nonrigid"]      = True
ops["nimg_init"]     = 400
ops["batch_size"]    = 200
ops["maxregshift"]   = 0.1
ops["smooth_sigma"]  = 1.15
ops["subpixel"]      = 10
ops["block_size"]    = [128, 128]
ops["snr_thresh"]    = 1.5
ops["maxregshiftNR"] = 5.0
ops["keep_movie_raw"] = True
ops["reg_tif"]       = True
ops["fast_disk"]     = out_dir

print("Converting TIFF to binary raw...")
io.tiff_to_binary(ops={**ops, "data_path": [tiff_dir], "save_path0": out_dir})

plane_dir = os.path.join(out_dir, "suite2p", "plane0")
ops = np.load(os.path.join(plane_dir, "ops.npy"), allow_pickle=True).item()

Ly, Lx  = ops["Ly"], ops["Lx"]
nframes = ops["nframes"]
f_raw = io.BinaryFile(Ly=Ly, Lx=Lx, filename=os.path.join(plane_dir, "data_raw.bin"), n_frames=nframes)
f_reg = io.BinaryFile(Ly=Ly, Lx=Lx, filename=os.path.join(plane_dir, "data.bin"),     n_frames=nframes)

print("Running motion correction (non-rigid)...")
reg_outputs = registration.registration_wrapper(
    f_reg=f_reg, f_raw=f_raw,
    f_reg_chan2=None, f_raw_chan2=None,
    refImg=None, align_by_chan2=False, ops=ops
)

refImg, rmin, rmax, meanImg, rigid_offsets, nonrigid_offsets = reg_outputs[:6]

np.save(os.path.join(plane_dir, "refImg.npy"),           refImg)
np.save(os.path.join(plane_dir, "meanImg.npy"),          meanImg)
np.save(os.path.join(plane_dir, "rigid_offsets.npy"),    rigid_offsets)
np.save(os.path.join(plane_dir, "nonrigid_offsets.npy"), nonrigid_offsets)
np.save(os.path.join(plane_dir, "registration_stats.npy"), {"rmin": rmin, "rmax": rmax})

print("Saved results successfully!")
print(json.dumps({"plane_dir": plane_dir}))

# =========================================================================
# APPEND THIS AT THE END: CONCATENATE THE CHUNKS GENERATED BY SUITE2P
# =========================================================================
import glob
import tifffile as tf

# The folder where Suite2p places the split files
reg_tif_dir = os.path.join(plane_dir, "reg_tif")
print(f"Concatenating chunks found in: {reg_tif_dir}")

# Find all .tif files created by Suite2p (file000_chan0.tif, file001_chan0.tif...)
chunks = sorted(glob.glob(os.path.join(reg_tif_dir, "*.tif")))

if chunks:
    # Path for the final complete output file
    final_output_path = os.path.join(plane_dir, "data_registered_complete.tif")
    print(f"Combining {len(chunks)} files into {final_output_path}...")

    # Open a BigTIFF writer and inject the small TIF chunks into it
    with tf.TiffWriter(final_output_path, bigtiff=True) as visual_tif:
        for chunk in chunks:
            # Read each Suite2p chunk and append it to the final file
            data_chunk = tf.imread(chunk)
            visual_tif.write(data_chunk, contiguous=True)

    print("Done concatenating!")
else:
    print("No chunks found to concatenate.")
    final_output_path = ""

# =========================================================================
print("Saved results successfully!")

# Returns the paths so the notebook knows where the final file is located
print(
    json.dumps(
        {
            "plane_dir": plane_dir,
            "reg_folder": reg_tif_dir,
            "registered_movie": final_output_path,
        }
    )
)

